version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf